const GAME_VERSION = 'v0.5.0';
const CHARACTERS = {
  male: [
    { id:'ren', name:'涼宮 蓮', tag:'傲嬌學霸', avatar:'♛', quote:'別誤會了，我只是順便幫你複習日文而已！', praise:'ふん、まあまあじゃない。', jpPraise:'ふん、まあまあじゃない。' },
    { id:'souta', name:'橘 奏太', tag:'溫柔會長', avatar:'✦', quote:'別太勉強自己，你的努力我一直看在眼裡。', praise:'素晴らしいですね！', jpPraise:'素晴らしいですね！' },
    { id:'rin', name:'黑羽 凜', tag:'霸道主唱', avatar:'♪', quote:'湊近一點，這句日文我只想唱給你聽。', praise:'もっと見せて。', jpPraise:'もっと見せて。' },
    { id:'haru', name:'白石 春', tag:'溫柔作家', avatar:'✒', quote:'每個單字都是一封還沒寄出的情書。', praise:'君の言葉、好きだよ。', jpPraise:'君の言葉、好きだよ。' },
    { id:'kai', name:'神谷 海', tag:'陽光運動系', avatar:'⚡', quote:'答對了！下一球……不，下一張也一起來吧！', praise:'すごい！最高だね！', jpPraise:'すごい！最高だね！' },
    { id:'yuki', name:'月城 雪', tag:'神秘轉學生', avatar:'☾', quote:'你聽見了嗎？這是屬於我們的秘密暗號。', praise:'君なら、できると思った。', jpPraise:'君なら、できると思った。' }
  ],
  female: [
    { id:'aoi', name:'櫻井 葵', tag:'傲嬌青梅', avatar:'🌸', quote:'笨蛋！過來我教你啦，才不是因為在意你。', praise:'調子に乗らないでよ！', jpPraise:'調子に乗らないでよ！' },
    { id:'suzu', name:'神樂 鈴', tag:'神秘巫女', avatar:'⛩', quote:'願神明的祝福，伴隨你的日語學習之旅。', praise:'見事な解密です。', jpPraise:'見事な解密です。' },
    { id:'ami', name:'星野 亞美', tag:'元氣後輩', avatar:'🎤', quote:'學長學長！快聽我剛寫好的日文新歌！', praise:'先輩最高ー！', jpPraise:'先輩最高ー！' },
    { id:'mio', name:'水瀨 澪', tag:'冷靜班長', avatar:'◇', quote:'很好，正確率又提高了。請保持這份專注。', praise:'完璧です。', jpPraise:'完璧です。' },
    { id:'nana', name:'藤原 菜奈', tag:'甜點研究社', avatar:'🍓', quote:'答對的獎勵是……下課一起吃草莓蛋糕？', praise:'おいしい！じゃなくて、すごい！', jpPraise:'すごい！' },
    { id:'rei', name:'鳴海 怜', tag:'貓系攝影師', avatar:'♢', quote:'笑一個。你的答案，剛好落在我鏡頭裡。', praise:'きれいに決まったね。', jpPraise:'きれいに決まったね。' }
  ]
};
const vocabPairs = [
  { id:1,jp:'好き',kana:'すき',zh:'喜歡' },{ id:2,jp:'約束',kana:'やくそく',zh:'約定' },{ id:3,jp:'秘密',kana:'ひみつ',zh:'秘密' },
  { id:4,jp:'友達',kana:'ともだち',zh:'朋友' },{ id:5,jp:'逢いたい',kana:'あいたい',zh:'想見你' },{ id:6,jp:'笑顔',kana:'えがお',zh:'笑容' }
];
const screens={title:document.querySelector('#title-screen'),select:document.querySelector('#select-screen'),game:document.querySelector('#game-screen'),result:document.querySelector('#result-screen')};
const $=(selector)=>document.querySelector(selector); $('#version-label').textContent=`Version ${GAME_VERSION}`; let currentRoute='male';let selectedChar=CHARACTERS.male[0];let currentMode='story';let flipped=[];let matched=0;let combo=0;let bestCombo=0;let affection=0;let locked=false;let startedAt=0;let soundOn=true;
function showScreen(name){Object.values(screens).forEach(s=>s.classList.remove('is-active'));screens[name].classList.add('is-active')}
function shuffle(list){return [...list].sort(()=>Math.random()-.5)}
function speak(text){if(!soundOn||!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='ja-JP';u.rate=.86;window.speechSynthesis.speak(u)}
function renderCharacters(){const list=CHARACTERS[currentRoute];$('#character-grid').innerHTML=list.map((c,i)=>`<button class="character-card ${c.id===selectedChar.id?'selected':''}" data-id="${c.id}" type="button"><span class="char-avatar">${c.avatar}</span><strong>${c.name}</strong><small>${c.tag}</small></button>`).join('');document.querySelectorAll('.character-card').forEach(card=>card.addEventListener('click',()=>{selectedChar=list.find(c=>c.id===card.dataset.id);renderCharacters();updatePreview()}))}
function updatePreview(){$('#selected-avatar').textContent=selectedChar.avatar;$('#selected-name').textContent=selectedChar.name;$('#selected-tag').textContent=`${selectedChar.tag} · 「${selectedChar.quote}」`}
function createCards(){const cards=shuffle(vocabPairs.flatMap(p=>[{...p,type:'jp',value:p.jp},{...p,type:'zh',value:p.zh}]));$('#card-grid').innerHTML=cards.map(c=>`<button class="card" type="button" data-id="${c.id}" data-type="${c.type}"><span class="card-inner"><span class="card-face card-front">✦</span><span class="card-face card-back ${c.type}"><strong>${c.value}</strong><small>${c.type==='jp'?c.kana:'中文意思'}</small></span></span></button>`).join('');document.querySelectorAll('.card').forEach(card=>card.addEventListener('click',()=>flipCard(card)))}
function updateAffection(){const value=Math.min(100,affection);$('#affection-value').textContent=String(value);$('#affection-bar b').style.width=`${value}%`}
function resetGame(){flipped=[];matched=0;combo=0;bestCombo=0;affection=0;locked=false;startedAt=Date.now();$('#combo').textContent='0';$('#progress-label').textContent=`解密進度 0 / ${vocabPairs.length}`;$('#progress-bar').style.width='0%';$('#message').textContent='先翻開一張卡牌，找出命運中的另一半。';$('#mode-badge').textContent=currentMode==='story'?'📖 主線解密劇情':'⚡ 純淨刷題模式';$('#partner-avatar').textContent=selectedChar.avatar;$('#partner-title').textContent=`${selectedChar.name} · ${selectedChar.tag}`;$('#dialogue-content').textContent=currentMode==='story'?selectedChar.quote:'準備好了嗎？專心配對，記住每個日文單字。';$('#scene-location').textContent=currentMode==='story'?'放學後的圖書館':'單字練習室';updateAffection();document.querySelectorAll('.choice-box button').forEach(b=>b.classList.remove('is-chosen'));createCards()}
function flipCard(card){if(locked||card.classList.contains('is-flipped')||card.classList.contains('is-matched'))return;card.classList.add('is-flipped');flipped.push(card);if(card.dataset.type==='jp'){const pair=vocabPairs.find(p=>String(p.id)===card.dataset.id);speak(pair.jp)}if(flipped.length===2)checkMatch()}
function checkMatch(){locked=true;const[a,b]=flipped;const correct=a.dataset.id===b.dataset.id&&a.dataset.type!==b.dataset.type;if(correct){matched++;combo++;bestCombo=Math.max(bestCombo,combo);affection+=10+combo;updateAffection(); a.classList.add('is-matched');b.classList.add('is-matched');$('#combo').textContent=String(combo);$('#progress-label').textContent=`解密進度 ${matched} / ${vocabPairs.length}`;$('#progress-bar').style.width=`${matched/vocabPairs.length*100}%`;const praise=currentMode==='story'?selectedChar.praise:'配對成功！繼續保持這個節奏。';$('#message').textContent=combo>=2?`心動連擊 ${combo}！${praise}`:praise;$('#dialogue-content').textContent=currentMode==='story'?`${selectedChar.jpPraise}（心動連擊 +${combo}）`:'Good! 單字記住了。';if(currentMode==='story')speak(selectedChar.jpPraise);flipped=[];locked=false;if(matched===vocabPairs.length)finishGame()}else{combo=0;$('#combo').textContent='0';$('#message').textContent='這兩張不是一組，再試試看！';setTimeout(()=>{a.classList.remove('is-flipped');b.classList.remove('is-flipped');flipped=[];locked=false},800)}}
function finishGame(){const seconds=Math.max(1,Math.round((Date.now()-startedAt)/1000));setTimeout(()=>{$('#final-combo').textContent=String(bestCombo);$('#final-time').textContent=String(seconds);$('#final-affection').textContent=`+${affection}`;$('#result-copy').textContent=currentMode==='story'?`${selectedChar.name} 的眼神，比剛才更靠近了一點。把今天的單字帶進下一場邂逅吧。`:'這一輪的單字都配對完成了。再玩一次，讓記憶變得更牢固。';showScreen('result')},650)}
$('#enter-btn').addEventListener('click',()=>{$('#intro-overlay').classList.add('dismissed');setTimeout(()=>$('#intro-overlay').remove(),850)});$('#start-btn').addEventListener('click',()=>{renderCharacters();updatePreview();showScreen('select')});$('.back-to-title').addEventListener('click',()=>showScreen('title'));document.querySelectorAll('.route-tab').forEach(tab=>tab.addEventListener('click',()=>{currentRoute=tab.dataset.route;selectedChar=CHARACTERS[currentRoute][0];document.querySelectorAll('.route-tab').forEach(t=>t.classList.remove('active'));tab.classList.add('active');renderCharacters();updatePreview()}));$('#practice-btn').addEventListener('click',()=>{resetGame();showScreen('game')});$('#quit-btn').addEventListener('click',()=>showScreen('select'));$('#again-btn').addEventListener('click',()=>{resetGame();showScreen('game')});$('#result-home-btn').addEventListener('click',()=>showScreen('title'));$('#mode-switch').addEventListener('click',()=>{currentMode=currentMode==='story'?'free':'story';$('#mode-badge').textContent=currentMode==='story'?'📖 主線解密劇情':'⚡ 純淨刷題模式';$('#dialogue-content').textContent=currentMode==='story'?selectedChar.quote:'準備好了嗎？專心配對，記住每個日文單字。'});$('#sound-btn').addEventListener('click',()=>{soundOn=!soundOn;$('#sound-btn').innerHTML=soundOn?'🔊 <span>發音開</span>':'🔇 <span>發音關</span>';if(!soundOn&&'speechSynthesis'in window)window.speechSynthesis.cancel()});$('#dialogue-sound').addEventListener('click',()=>speak(currentMode==='story'?selectedChar.jpPraise:'日本語の勉強を楽しんでください。'));document.querySelectorAll('.choice-box button').forEach(button=>button.addEventListener('click',()=>{if(currentMode!=='story')return;document.querySelectorAll('.choice-box button').forEach(b=>b.classList.remove('is-chosen'));button.classList.add('is-chosen');const study=button.dataset.choice==='study';affection+=study?8:5;updateAffection();$('#dialogue-content').textContent=study?`${selectedChar.name}：「……嗯，這樣才乖。那我們一起念一次。」`:`${selectedChar.name}：「呵，這種氣勢很好。那就用實力證明給我看。」`;$('#message').textContent=study?'你的回答讓距離悄悄拉近了。':'你們之間的火花，好像更亮了一點。';if(study)speak('一緒に勉強しましょう。');}));
